# docker-compose up -d
# docker-compose down

version: "3.6"
networks:
  localdev:
    name: localdev

services:     
  boilerplate-api:
    entrypoint: ["dotnet", "Boilerplate.Api.dll"]
    build:
      context: .
      dockerfile: src/Boilerplate.Api/Dockerfile
    image: boilerplate-api:local
    container_name: boilerplate-api    
    networks:
      - localdev
    volumes:
      - ./etc/wait-for.sh:/app/wait-for.sh
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - localdev